// lib/symbol/v5/shareEngine.ts
// V5: Share Engine — 裂变生成器

export interface SharePayload {
  title: string;
  subtitle: string;
  metrics: {
    load: number;
    state: string;
    volatility: number;
  };
  warning: string;
  cta: string;
}

export function generateSharePayload(output: any): SharePayload {
  const score = output.user_profile?.intensity_score || 50;
  const archetype = output.user_profile?.archetype || 'Unknown';
  const dominantState = output.emotion_system?.dominant_state || 'neutral';
  const volatility = output.emotion_system?.volatility || 0.5;

  const hookMap = [
    `My system load is ${score}. Most people don't realize what this means.`,
    `I was diagnosed as "${archetype}". It explained everything.`,
    `This is what my mind looks like under pressure.`,
  ];

  const selectedHook = hookMap[Math.floor(Math.random() * hookMap.length)];

  return {
    title: selectedHook,
    subtitle: 'Generated by System Diagnostic Engine',
    metrics: {
      load: score,
      state: dominantState,
      volatility: Math.round(volatility * 100) / 100,
    },
    warning: "Most people don't see this clearly about themselves.",
    cta: 'Run your system check →',
  };
}
